-- Generated by `ouroctl test --generate`: one story per state each chart
-- reaches, at the end of the first path that reached it (design/statecharts.md
-- section 14). Regenerate instead of editing. Optional story_views.lua maps
-- chart ids to view functions; other charts render a state panel.
--   ouroctl storybook snapshot states.stories.lua --output <dir>
local ouro = require('ouro')
for _, name in ipairs({'app', 'window', 'layer_surface', 'lock_surface'}) do
  if ouro[name] == nil then ouro[name] = function(t) return t end end
end
ouro.xdg = ouro.xdg or {}
ouro.xdg.paths = ouro.xdg.paths or function(id)
  local root = '/nonexistent/ourokit-stories/'
  return {config = root .. 'config/' .. id, data = root .. 'data/' .. id, state = root .. 'state/' .. id,
    cache = root .. 'cache/' .. id, config_dirs = {}, data_dirs = {}}
end
require("app")
local has_views, views = pcall(require, 'story_views')
local decode = ouro.machine._json_decode
local values = {}
local plan = {values = values, charts = {
  {chart = "stopwatch", input = decode([=[{}]=]).input, states = {
    {state = "clock", steps = decode([=[[]]=]), inputs = decode([=[[]]=])},
    {state = "clock.idle", steps = decode([=[[]]=]), inputs = decode([=[[]]=])},
    {state = "clock.paused", steps = decode([=[["START","STOP"]]=]), inputs = decode([=[[{"a":"stopwatch","e":{"type":"START"},"k":"event"},{"a":"stopwatch","e":{"type":"STOP"},"k":"event"}]]=])},
    {state = "clock.running", steps = decode([=[["START"]]=]), inputs = decode([=[[{"a":"stopwatch","e":{"type":"START"},"k":"event"}]]=])},
    {state = "settings", steps = decode([=[[]]=]), inputs = decode([=[[]]=])},
    {state = "settings.closed", steps = decode([=[[]]=]), inputs = decode([=[[]]=])},
    {state = "settings.open", steps = decode([=[["OPEN_SETTINGS"]]=]), inputs = decode([=[[{"a":"stopwatch","e":{"type":"OPEN_SETTINGS"},"k":"event"}]]=])},
  }},
}}
return ouro.machine.state_stories(plan, has_views and views or nil)
