-- Generated by `ouroctl test --generate`: one story per state each chart
-- reaches, at the end of the first path that reached it (design/statecharts.md
-- section 14). Regenerate instead of editing. Optional story_views.lua maps
-- chart ids to view functions; other charts render a state panel.
--   ouroctl storybook snapshot states.stories.lua --output <dir>
local ouro = require('ouro')
for _, name in ipairs({'app', 'window', 'layer_surface', 'lock_surface'}) do
  if ouro[name] == nil then ouro[name] = function(t) return t end end
end
ouro.xdg = ouro.xdg or {}
ouro.xdg.paths = ouro.xdg.paths or function(id)
  local root = '/nonexistent/ourokit-stories/'
  return {config = root .. 'config/' .. id, data = root .. 'data/' .. id, state = root .. 'state/' .. id,
    cache = root .. 'cache/' .. id, config_dirs = {}, data_dirs = {}}
end
require("app")
local has_views, views = pcall(require, 'story_views')
return ouro.machine.state_stories(ouro.json.decode([=[
{"charts":[{"chart":"stopwatch","states":[{"inputs":{},"state":"clock","steps":[]},{"inputs":{},"state":"clock.idle","steps":[]},{"inputs":[{"a":"stopwatch","e":{"type":"START"},"k":"event"},{"a":"stopwatch","e":{"type":"STOP"},"k":"event"}],"state":"clock.paused","steps":["START","STOP"]},{"inputs":[{"a":"stopwatch","e":{"type":"START"},"k":"event"}],"state":"clock.running","steps":["START"]},{"inputs":{},"state":"settings","steps":[]},{"inputs":{},"state":"settings.closed","steps":[]},{"inputs":[{"a":"stopwatch","e":{"type":"OPEN_SETTINGS"},"k":"event"}],"state":"settings.open","steps":["OPEN_SETTINGS"]}]}]}
]=]), has_views and views or nil)
