-- Generated by `ouroctl test --generate`: one story per state each chart
-- reaches, at the end of the first path that reached it (design/statecharts.md
-- section 14). Regenerate instead of editing. Optional story_views.lua maps
-- chart ids to view functions; other charts render a state panel.
--   ouroctl storybook snapshot states.stories.lua --output <dir>
local ouro = require('ouro')
for _, name in ipairs({'app', 'window', 'layer_surface', 'lock_surface'}) do
  if ouro[name] == nil then ouro[name] = function(t) return t end end
end
ouro.xdg = ouro.xdg or {}
ouro.xdg.paths = ouro.xdg.paths or function(id)
  local root = '/nonexistent/ourokit-stories/'
  return {config = root .. 'config/' .. id, data = root .. 'data/' .. id, state = root .. 'state/' .. id,
    cache = root .. 'cache/' .. id, config_dirs = {}, data_dirs = {}}
end
require("app")
local has_views, views = pcall(require, 'story_views')
local decode = ouro.machine._json_decode
local values = {}
values[1] = decode([=[{"value":"generated error"}]=]).value
values[2] = decode([=[{"value":[{"actions":[],"comment":null,"dbus_activatable":false,"exec":"org.gnome.Terminal","generic_name":"Terminal emulator","hidden":false,"icon":null,"id":"org.gnome.Terminal.desktop","keywords":["shell"],"name":"Terminal","no_display":false,"path":"/apps/org.gnome.Terminal.desktop","terminal":false,"visible":true,"working_directory":null},{"actions":[],"comment":"Browse the web","dbus_activatable":false,"exec":"firefox","generic_name":null,"hidden":false,"icon":null,"id":"firefox.desktop","keywords":[],"name":"Firefox","no_display":false,"path":"/apps/firefox.desktop","terminal":false,"visible":true,"working_directory":null}]}]=]).value
local plan = {values = values, charts = {
  {chart = "launcher", input = decode([=[{}]=]).input, states = {
    {state = "hidden", steps = decode([=[[]]=]), inputs = decode([=[[]]=])},
    {state = "open", steps = decode([=[["OPEN"]]=]), inputs = decode([=[[{"a":"launcher","e":{"type":"OPEN"},"k":"event"}]]=])},
    {state = "open.failed", steps = decode([=[["OPEN","error.invoke.scan"]]=]), inputs = decode([=[[{"a":"launcher","e":{"type":"OPEN"},"k":"event"},{"a":"launcher","id":"scan","k":"invoke","ok":false,"synthetic":true,"vref":1}]]=])},
    {state = "open.launching", steps = decode([=[["OPEN","done.invoke.scan","ACTIVATE"]]=]), inputs = decode([=[[{"a":"launcher","e":{"type":"OPEN"},"k":"event"},{"a":"launcher","id":"scan","k":"invoke","ok":true,"vref":2},{"a":"launcher","e":{"type":"ACTIVATE"},"k":"event"}]]=])},
    {state = "open.loading", steps = decode([=[["OPEN"]]=]), inputs = decode([=[[{"a":"launcher","e":{"type":"OPEN"},"k":"event"}]]=])},
    {state = "open.ready", steps = decode([=[["OPEN","done.invoke.scan"]]=]), inputs = decode([=[[{"a":"launcher","e":{"type":"OPEN"},"k":"event"},{"a":"launcher","id":"scan","k":"invoke","ok":true,"vref":2}]]=])},
  }},
}}
return ouro.machine.state_stories(plan, has_views and views or nil)
