-- Generated by `ouroctl test --generate`: one story per state each chart
-- reaches, at the end of the first path that reached it (design/statecharts.md
-- section 14). Regenerate instead of editing. Optional story_views.lua maps
-- chart ids to view functions; other charts render a state panel.
--   ouroctl storybook snapshot states.stories.lua --output <dir>
local ouro = require('ouro')
for _, name in ipairs({'app', 'window', 'layer_surface', 'lock_surface'}) do
  if ouro[name] == nil then ouro[name] = function(t) return t end end
end
ouro.xdg = ouro.xdg or {}
ouro.xdg.paths = ouro.xdg.paths or function(id)
  local root = '/nonexistent/ourokit-stories/'
  return {config = root .. 'config/' .. id, data = root .. 'data/' .. id, state = root .. 'state/' .. id,
    cache = root .. 'cache/' .. id, config_dirs = {}, data_dirs = {}}
end
require("app")
local has_views, views = pcall(require, 'story_views')
local decode = ouro.machine._json_decode
local values = {}
values[1] = decode([=[{"value":"file:///tmp/note.ournote"}]=]).value
values[2] = decode([=[{"value":null}]=]).value
local plan = {values = values, charts = {
  {chart = "document", input = decode([=[{"input":{}}]=]).input, states = {
    {state = "closed", steps = decode([=[["CLOSE"]]=]), inputs = decode([=[[{"a":"document","e":{"type":"CLOSE"},"k":"event"}]]=])},
    {state = "open", steps = decode([=[[]]=]), inputs = decode([=[[]]=])},
    {state = "open.io", steps = decode([=[[]]=]), inputs = decode([=[[]]=])},
    {state = "open.io.idle", steps = decode([=[[]]=]), inputs = decode([=[[]]=])},
    {state = "open.io.saving", steps = decode([=[["SAVE"]]=]), inputs = decode([=[[{"a":"document","e":{"type":"SAVE"},"k":"event"}]]=])},
    {state = "open.io.saving.choosing", steps = decode([=[["SAVE"]]=]), inputs = decode([=[[{"a":"document","e":{"type":"SAVE"},"k":"event"}]]=])},
    {state = "open.io.saving.writing", steps = decode([=[["SAVE","done.invoke.choose"]]=]), inputs = decode([=[[{"a":"document","e":{"type":"SAVE"},"k":"event"},{"a":"document","id":"choose","k":"invoke","ok":true,"vref":1}]]=])},
    {state = "open.lifecycle", steps = decode([=[[]]=]), inputs = decode([=[[]]=])},
    {state = "open.lifecycle.active", steps = decode([=[[]]=]), inputs = decode([=[[]]=])},
    {state = "open.lifecycle.confirming", steps = decode([=[["EDIT","CLOSE"]]=]), inputs = decode([=[[{"a":"document","e":{"field":"text","type":"EDIT","value":"title"},"k":"event"},{"a":"document","e":{"type":"CLOSE"},"k":"event"}]]=])},
    {state = "open.lifecycle.confirming.awaiting", steps = decode([=[["EDIT","CLOSE","SAVE"]]=]), inputs = decode([=[[{"a":"document","e":{"field":"text","type":"EDIT","value":"title"},"k":"event"},{"a":"document","e":{"type":"CLOSE"},"k":"event"},{"a":"document","e":{"type":"SAVE"},"k":"event"}]]=])},
    {state = "open.lifecycle.confirming.prompt", steps = decode([=[["EDIT","CLOSE"]]=]), inputs = decode([=[[{"a":"document","e":{"field":"text","type":"EDIT","value":"title"},"k":"event"},{"a":"document","e":{"type":"CLOSE"},"k":"event"}]]=])},
  }},
  {chart = "notes", input = decode([=[{}]=]).input, states = {
    {state = "exited", steps = decode([=[["CLOSE_WINDOW","done.invoke.quit"]]=]), inputs = decode([=[[{"a":"notes","e":{"type":"CLOSE_WINDOW"},"k":"event"},{"a":"notes","id":"quit","k":"invoke","ok":true,"vref":2}]]=])},
    {state = "quitting", steps = decode([=[["CLOSE_WINDOW"]]=]), inputs = decode([=[[{"a":"notes","e":{"type":"CLOSE_WINDOW"},"k":"event"}]]=])},
    {state = "running", steps = decode([=[[]]=]), inputs = decode([=[[]]=])},
    {state = "running.closing", steps = decode([=[["CLOSE_WINDOW"]]=]), inputs = decode([=[[{"a":"notes","e":{"type":"CLOSE_WINDOW"},"k":"event"}]]=])},
    {state = "running.closing.prompting", steps = decode([=[["ADD","EDIT","CLOSE_WINDOW"]]=]), inputs = decode([=[[{"a":"notes","e":{"type":"ADD"},"k":"event"},{"a":"notes/document.1","e":{"field":"title","type":"EDIT","value":"title"},"k":"event"},{"a":"notes","e":{"type":"CLOSE_WINDOW"},"k":"event"}]]=])},
    {state = "running.closing.walking", steps = decode([=[["CLOSE_WINDOW"]]=]), inputs = decode([=[[{"a":"notes","e":{"type":"CLOSE_WINDOW"},"k":"event"}]]=])},
    {state = "running.open", steps = decode([=[[]]=]), inputs = decode([=[[]]=])},
  }},
}}
return ouro.machine.state_stories(plan, has_views and views or nil)
