-- Generated by `ouroctl test --generate`: one story per state each chart
-- reaches, at the end of the first path that reached it (design/statecharts.md
-- section 14). Regenerate instead of editing. Optional story_views.lua maps
-- chart ids to view functions; other charts render a state panel.
--   ouroctl storybook snapshot states.stories.lua --output <dir>
local ouro = require('ouro')
for _, name in ipairs({'app', 'window', 'layer_surface', 'lock_surface'}) do
  if ouro[name] == nil then ouro[name] = function(t) return t end end
end
ouro.xdg = ouro.xdg or {}
ouro.xdg.paths = ouro.xdg.paths or function(id)
  local root = '/nonexistent/ourokit-stories/'
  return {config = root .. 'config/' .. id, data = root .. 'data/' .. id, state = root .. 'state/' .. id,
    cache = root .. 'cache/' .. id, config_dirs = {}, data_dirs = {}}
end
require("app")
local has_views, views = pcall(require, 'story_views')
local decode = ouro.json.decode
local values = {}
values[1] = decode([=[{"value":null}]=]).value
values[2] = decode([=[{"value":"generated error"}]=]).value
values[3] = decode([=[{"value":{"contacts":[{"email":"ada@example.org","id":"ada","name":"Ada Lovelace"},{"email":"grace@example.org","id":"grace","name":"Grace Hopper"}]}}]=]).value
values[4] = decode([=[{"value":{"message":"offline"}}]=]).value
local plan = {values = values, charts = {
  {chart = "appearance", input = decode([=[{}]=]).input, states = {
    {state = "shown", steps = decode([=[[]]=]), inputs = decode([=[[]]=])},
  }},
  {chart = "contacts", input = decode([=[{}]=]).input, states = {
    {state = "exited", steps = decode([=[["QUIT","done.invoke.exit"]]=]), inputs = decode([=[[{"a":"contacts","e":{"type":"QUIT"},"k":"event"},{"a":"contacts","id":"exit","k":"invoke","ok":true,"vref":1}]]=])},
    {state = "exiting", steps = decode([=[["QUIT"]]=]), inputs = decode([=[[{"a":"contacts","e":{"type":"QUIT"},"k":"event"}]]=])},
    {state = "failed", steps = decode([=[["error.invoke.load"]]=]), inputs = decode([=[[{"a":"contacts","id":"load","k":"invoke","ok":false,"vref":2}]]=])},
    {state = "loading", steps = decode([=[[]]=]), inputs = decode([=[[]]=])},
    {state = "ready", steps = decode([=[["done.invoke.load"]]=]), inputs = decode([=[[{"a":"contacts","id":"load","k":"invoke","ok":true,"vref":3}]]=])},
    {state = "ready.sync", steps = decode([=[["done.invoke.load"]]=]), inputs = decode([=[[{"a":"contacts","id":"load","k":"invoke","ok":true,"vref":3}]]=])},
    {state = "ready.sync.idle", steps = decode([=[["done.invoke.load"]]=]), inputs = decode([=[[{"a":"contacts","id":"load","k":"invoke","ok":true,"vref":3}]]=])},
    {state = "ready.sync.retrying", steps = decode([=[["done.invoke.load","RENAME","error.invoke.save"]]=]), inputs = decode([=[[{"a":"contacts","id":"load","k":"invoke","ok":true,"vref":3},{"a":"contacts","e":{"id":"ada","name":"pending","type":"RENAME"},"k":"event"},{"a":"contacts","id":"save","k":"invoke","ok":false,"vref":4}]]=])},
    {state = "ready.sync.saving", steps = decode([=[["done.invoke.load","RENAME"]]=]), inputs = decode([=[[{"a":"contacts","id":"load","k":"invoke","ok":true,"vref":3},{"a":"contacts","e":{"id":"ada","name":"pending","type":"RENAME"},"k":"event"}]]=])},
    {state = "ready.lifecycle", steps = decode([=[["done.invoke.load"]]=]), inputs = decode([=[[{"a":"contacts","id":"load","k":"invoke","ok":true,"vref":3}]]=])},
    {state = "ready.lifecycle.quitting", steps = decode([=[["done.invoke.load","QUIT"]]=]), inputs = decode([=[[{"a":"contacts","id":"load","k":"invoke","ok":true,"vref":3},{"a":"contacts","e":{"type":"QUIT"},"k":"event"}]]=])},
    {state = "ready.lifecycle.running", steps = decode([=[["done.invoke.load"]]=]), inputs = decode([=[[{"a":"contacts","id":"load","k":"invoke","ok":true,"vref":3}]]=])},
  }},
}}
return ouro.machine.state_stories(plan, has_views and views or nil)
