"""Collect unmodified upstream notices for the pinned image dependencies.

Usage: python3 tools/image/generate_notices.py WUFFS_SOURCE LIBWEBP_SOURCE
Requires Cargo/Rust on PATH. Does not update the Cargo lockfile.
"""
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys

root = Path(__file__).resolve().parents[2]
dest = root / "tools/image"
metadata = json.loads(subprocess.check_output([
    os.environ.get("CARGO", "cargo"), "metadata", "--locked", "--format-version", "1",
    "--manifest-path", str(root / "src/image/resvg/Cargo.toml"),
]))
sections = ["Ourokit image codec third-party notices\n"
            "Generated by tools/image/generate_notices.py. Preserve with binary distributions.\n"
            "Cargo versions/checksums: src/image/resvg/Cargo.lock.\n"
            "Rust standard-library notices: RUST_LIBRARY_LICENSES.html (Rust 1.94.0).\n"]

def append(name, directory, files):
    sections.append("\n" + "=" * 78 + "\n" + name + "\n")
    for file in files:
        sections.append("\n--- " + str(file) + " ---\n" + (directory / file).read_text())

append("Wuffs 0f214ba59c20c0c9c7ba841ecc3683f863965312; https://github.com/google/wuffs",
       Path(sys.argv[1]), ["LICENSE", "AUTHORS"])
append("libwebp 1.6.0; https://github.com/webmproject/libwebp",
       Path(sys.argv[2]), ["COPYING", "PATENTS", "AUTHORS"])
for package in sorted(metadata["packages"], key=lambda p: (p["name"], p["version"])):
    if package["name"] == "ourokit-resvg":
        continue
    directory = Path(package["manifest_path"]).parent
    files = sorted(p.name for p in directory.iterdir() if p.is_file() and
                   p.name.lower().startswith(("license", "copying", "notice", "unlicense")))
    if not files:
        raise RuntimeError("No upstream license found: " + package["name"])
    append(f'{package["name"]} {package["version"]}; {package["license"]}; {package.get("repository") or package["source"]}',
           directory, files)
sysroot = Path(subprocess.check_output(["rustc", "--print", "sysroot"], text=True).strip())
rust_version = subprocess.check_output(["rustc", "--version"], text=True).strip()
if not rust_version.startswith("rustc 1.94.0 "):
    raise RuntimeError("Generate the checked-in Rust notices with Rust 1.94.0")
shutil.copyfile(sysroot / "share/doc/rust/COPYRIGHT-library.html", dest / "RUST_LIBRARY_LICENSES.html")
(dest / "THIRD_PARTY_NOTICES.txt").write_text("\n".join(sections))
